### ISSUE TITLE
Add support for experimental `classProperties` Babel plugin

### ISSUE THREAD

**Issue by NullVoxPopuli** [simplabs/ember-intl-analyzer#64]
```
 $ yarn lint:i18n
yarn run v1.17.3
$ npx ember-intl-analyzer
[1/4] 🔍  Finding JS and HBS files...
[2/4] 🔍  Searching for translations keys in JS and HBS files...
SyntaxError: This experimental syntax requires enabling the parser plugin: 'classProperties' (6:21)
    at Parser.raise (/home/lprestonsegoiii/.npm/_npx/12695/lib/node_modules/ember-intl-analyzer/node_modules/@babel/parser/lib/index.js:6325:17)
    at Parser.expectPlugin (/home/lprestonsegoiii/.npm/_npx/12695/lib/node_modules/ember-intl-analyzer/node_modules/@babel/parser/lib/index.js:7647:18)
    at Parser.parseClassProperty (/home/lprestonsegoiii/.npm/_npx/12695/lib/node_modules/ember-intl-analyzer/node_modules/@babel/parser/lib/index.js:10830:12)
    at Parser.pushClassProperty (/home/lprestonsegoiii/.npm/_npx/12695/lib/node_modules/ember-intl-analyzer/node_modules/@babel/parser/lib/index.js:10795:30)
    at Parser.parseClassMemberWithIsStatic (/home/lprestonsegoiii/.npm/_npx/12695/lib/node_modules/ember-intl-analyzer/node_modules/@babel/parser/lib/index.js:10734:14)
    at Parser.parseClassMember (/home/lprestonsegoiii/.npm/_npx/12695/lib/node_modules/ember-intl-analyzer/node_modules/@babel/parser/lib/index.js:10668:10)
    at withTopicForbiddingContext (/home/lprestonsegoiii/.npm/_npx/12695/lib/node_modules/ember-intl-analyzer/node_modules/@babel/parser/lib/index.js:10623:14)
    at Parser.withTopicForbiddingContext (/home/lprestonsegoiii/.npm/_npx/12695/lib/node_modules/ember-intl-analyzer/node_modules/@babel/parser/lib/index.js:9702:14)
    at Parser.parseClassBody (/home/lprestonsegoiii/.npm/_npx/12695/lib/node_modules/ember-intl-analyzer/node_modules/@babel/parser/lib/index.js:10600:10)
    at Parser.parseClass (/home/lprestonsegoiii/.npm/_npx/12695/lib/node_modules/ember-intl-analyzer/node_modules/@babel/parser/lib/index.js:10574:22)
```

is there a way to tell this to use my project's babel config?
I'm using typescript w/ octane

**Comment by Turbo87** [comment]
I'm assuming we need to add something [here](https://github.com/simplabs/ember-intl-analyzer/blob/master/index.js#L142)
